### PR TITLE
New Update Mechanism

### PR DESCRIPTION
**Pull request by jthrilly**
This PR replaces  electron-updater with the same system used in https://github.com/complexdatacollective/Interviewer/pull/1091

Please see that PR for details.

### CODE REVIEW

**Comment by rebeccamadsen** [comment]
Installing the release build, I get an error about missing fs-extra:

install error

**Comment by jthrilly** [comment]
That's pretty annoying. Doesn't seem to be to do with anything I have changed here, so I suspect it crept in from updating something else.

**Review by rebeccamadsen — APPROVED** [review]
Looks good to me!

**Comment by rebeccamadsen** [comment]
This doesn't prompt me to upgrade my version when I set the version to 5.0.0 anymore. But the inability to open protocols crops up for me in release builds here, so I'm not sure if it's related.

**Comment by jthrilly** [comment]
Should be fixed now @rebeccamadsen

**Comment by rebeccamadsen** [comment]
This fixes the version check, but the "Show Release Notes" button just gives this error:

```
Uncaught TypeError: Cannot read property 'buttonText' of undefined
    at c (main.829d3f0e.js:148)
    at onClick (main.829d3f0e.js:148)
    at l (main.829d3f0e.js:33)
    at Object.s (main.829d3f0e.js:65)
    at d (main.829d3f0e.js:65)
    at main.829d3f0e.js:65
    at v (main.829d3f0e.js:65)
    at ot (main.829d3f0e.js:65)
    at it (main.829d3f0e.js:65)
    at st (main.829d3f0e.js:65)
    at dt (main.829d3f0e.js:65)
    at q (main.829d3f0e.js:65)
    at B (main.829d3f0e.js:65)
    at Qt (main.829d3f0e.js:65)
    at Kt (main.829d3f0e.js:65)
    at t.unstable_runWithPriority (main.829d3f0e.js:73)
```

**Review by rebeccamadsen — APPROVED** [review]
Everything looks great now!

**Pull request merged**
