### PR TITLE
Refreshed Home Screen

### LINKED ISSUE #433: Open React-Select does not follow "window" scroll
Can be seen when editing an EditableList item, such as a prompt.

Could be:
- Intended behaviour
- Issue with our implementation

If issue with our implementation we should update to fix.

Screenshot 2019-03-26 at 18 04 11

### LINKED ISSUE #637: Better styling needed for nested sections
We have several areas of Architect where UI "sections" are nested within each other. This creates styling issues, since these must be separated visually.

I propose consistent styling for these sections based on their "depth", with each level setting an appropriate background color, and setting CSS variables such as `--input-background` appropriately.

Quick experiments to give some inspiration:

Screen Shot 2020-05-18 at 1 47 22 PM
Screen Shot 2020-05-18 at 1 47 17 PM
Screen Shot 2020-05-18 at 1 44 19 PM
Screen Shot 2020-05-18 at 1 44 15 PM

### PR DESCRIPTION
**Pull request by jthrilly**
This PR Refreshes the look and feel of Architect for 6.0.0. It contains many quality of life improvements, user interface improvements, and small fixes to usability issues.

- NativeSelect component replaces react-select. Includes an inline "Create New" option. This is now used as the variable chooser/creator. Fixes #433 
- Corrected scrollbar behaviour by replacing numerous uses of absolutely positioned elements with flexbox layouts.
- Redesigned the homescreen from the ground up, including UI elements from the latest UI package release
- Made button location and text consistent throughout the app
- Added section styling based on level, and applied clear sectioning to all app screens. Fixes #637 
- Redesigned the overview card
- Redesigned the state edit screen to include a header summary panel that contains a stage previous, the entity selector, and skiplogic/node filtering.

As with the NC PR, there are simply too many code changes to review this in that level of detail. Please test by using the app, and reporting any obvious bugs with the above features. 

Outstanding issues:
- [x] Protocols opened but not saved don't have a correct `lastUpdated` prop set when displayed on the start screen
- [x] App test won't pass. Seems to be failing to shallow render, but not sure why. 
- [x] Migration feature hasn't been tested
- [x] Update feature is not implemented (to be done in future PR - link here)
- [x] Tip panel not implemented.

### CODE REVIEW

**Comment by jthrilly** [comment]
Outstanding issues:

- [ ] Welcome message animation has visual glitch (white background element?) when box shadow is applied.
- [ ] Store welcome message show/hide and what's new dismissed state in redux as normal (dont use local storage hook).
- [ ] Update use of `<GraphicButton>` and `<ProtocolCard>` to UI versions. 
- [ ] Update header graphic
- [ ] Finish tip implementation, or else remove for now
- [ ] No exit animation when "whats new" is dismissed
- [ ] Add in recent documents as per the following screenshot:

Screen Shot 2020-08-05 at 2 34 03 PM

**Comment by wwqrd** [comment]
> Store welcome message show/hide and what's new dismissed state in redux as normal (dont use local storage hook).
What's 
These are already stored in redux :tada:

**Comment by wwqrd** [comment]
- [x] Release notes link throws an error
- [ ] can't dismiss what's new
- [ ] no close screen animation?
- [ ] creating a protocol adds it to recent protocols list
- [ ] clear storage data doesn't seem to work?

**Comment by jthrilly** [comment]
>     * clear storage data doesn't seem to work?
Yeah, this was the case when it was picked up. You have to click it twice. No idea why.

**Comment by wwqrd** [comment]
> Yeah, this was the case when it was picked up. You have to click it twice. No idea why.

Sorry this was just my notes for what I'm fixing, not intended as a review

**Comment by rebeccamadsen** [comment]
This looks slick! Not an exhaustive review, but I did notice some things worth mentioning:

- if you add a new stage before the first stage, the NC preview is in the wrong order and shows the new stage last. If you save and come back to edit the stage, though, the preview is correct.
- when adding a new stage after the last stage, preview doesn't work at all until you save and come back in.
- resume editing lists the same protocol multiple times
resume editing duplicates

**Comment by wwqrd** [comment]
Using the last add screen button actually adds it to the start.

**Comment by wwqrd** [comment]
Preview (remote), doesn't work with latest version of Network Canvas.

Screenshot from 2020-10-21 12-07-39

**Comment by wwqrd** [comment]
> - if you add a new stage before the first stage, the NC preview is in the wrong order and shows the new stage last. If you save and come back to edit the stage, though, the preview is correct.

I can't actually recreate this one? Can you give some more information and/or any illustration?

> - resume editing lists the same protocol multiple times

This should now be fixed

> - when adding a new stage after the last stage, preview doesn't work at all until you save and come back in.

Working on this one now

**Comment by wwqrd** [comment]
> - when adding a new stage after the last stage, preview doesn't work at all until you save and come back in.

Fixed by 7067f97

**Comment by rebeccamadsen** [comment]
The latest helps with most things. This is the "adding before the first stage" issue I mentioned. When I add a stage before the first existing stage:

add before first

The NC preview will show this at the end of the stages in preview mode:

last stage

Even though it is inserted at the beginning of all the stages:

first stage

Going back into the edit stage, I can then preview NC and it is in the expected order.

**Comment by jthrilly** [comment]
Could it be that inserting a stage needs to either close or refresh the preview, rather than just updating the protocol?

**Comment by wwqrd** [comment]
Thanks @rebeccamadsen that's fixed now

**Comment by rebeccamadsen** [comment]
Looks great! Let me know if there are more changes that need eyes.

**Review by wwqrd — APPROVED** [review]

**Pull request merged**
