### PR TITLE
User interface overhaul/refactor

### PR DESCRIPTION
**Pull request by jthrilly**
This PR represents a substantial and deep UI overhaul for Architect, with the aim of fixing several outstanding usability and user experience issues.

Specifically:

- **The main structure of the app has been revised**
  - The start screen and the timeline are now the only "full screen" views. All sub views, including the stage editor, are now "modal" style.
  - Screens include: all stage editors (triggered by clicking a stage from the timeline), all secondary protocol views (codebook, resource library, printable summary), and the new stage screen.
  - There are instances of nested screens, such as prompt editing, new variable creation within a stage editor, and so on. We believed that these situations would be visually confusing to present as multiple overlapping modals, but it turns out that this is not the case, as long as the rules about modals above are observed. 
  - Removed use of `window` component and replaced with `createPortal`, and harmonized all modal styles for consistency
- **The `<Section>` component has been overhauled**
  - Revised "section" styles to use the html `fieldset` and `legend` tags. 
  - Reimplements expandable sections within this paradigm. Optional sections now contain a toggle which can be used to expand the section and use the feature.
  - Adds a red required asterisk indicator to sections that contain required elements. 
  - Adds consistent button footers and headers to all screens and modals
- **New stage screen has been overhauled**
  - Now supports keyboard navigation
  - Keywords and descriptions for all interfaces have been updated 
  - 'Tags' are now capability oriented, and dynamically disable in response to available options
- **The name generator roster edit screen has been implemented** 
- **Micro interactions added**
  - Tip icon animates when in view
  - Stage header component that collapses into a fixed position header
summary when the screen scrolls
  - Added interface documentation link to header of stage editor
  - Added keyboard shortcut (cmd + forward slash) to open the code view in the stage editor
- **New 'EntitySelectField` component**
  - replaces all instances where a node or edge type is required
  - uses the new variable pill style
  - allows inline node/edge type creation
  - automatically switches to newly created node/edge types if no other values present
  - optionally prompts before changing value, and provides a callback when changing that is used to reset other parts of the form
- **Removed substantial duplication from stage editor sections**
    - Prompt components now shared where possible, and sections reused throughout interface editors
- **Substantially revised filter/skip logic rule previewing** 
  - Rule previews now have better grammar, and use PreviewNode/PreviewEdge and VariablePill

## Backend changes
- Updated framer motion to 5.x
  - Webpack config updated with alias to account for mjs bug in CRA
- Updated react-sortable-hoc to 2.x
- Updated UI lib
- Updated development protocol
- Updated protocol scheme
- Deleted:
  - `ContextPanel`
  - `Details`
  - `EdgeSelect`
  - `NodeSelect`
  - `OrderBy`
  - `ExpandableItem`
  - `EditAlterRule`
  - `EditEdgeRule`
  - `useTagList`
  - Various prompt field sections

## Bugs fixed
- Timeline now scrolls when dragging stages
- Skip logic/filter edge rules can now target edge attributes
- New stage screen now correctly indexes interface keywords
- Correct use of units and CSS variables throughout the app

### CODE REVIEW

**Comment by rebeccamadsen** [comment]
- [ ] have to save a screen before "preview" works when creating a stage at the beginning (e.g. doesn't work while creating first interface)
- [ ] preview button made architect freeze when creating a new stage at the end only (worked after saving it)
- [ ] add stage to end adds to the beginning instead of end
- [ ] sort options on roster starts enabled; have to click twice to disable
- [ ] skip logic will clear when you toggle the skip logic, but it doesn't actually toggle/disable skip logic unless you click again
- [ ] new variable, input control types list has categories above the types instead of interspersed
- [ ] sociogram did not require selecting edge or variable toggling though marked required (various other stages are similar, but haven't made a comprehensive list yet)
- [ ] sociogram display edge option for the edge just selected doesn't work unless you select the display before selecting the edge to create
- [ ] rosters need updated pictures

**Comment by rebeccamadsen** [comment]
- [ ] Narrative preset group variable has a double error message: image
- [ ] Marked required, but not actually required:
* Narrative preset "Edge Types to Display"
* Narrative preset "Highlight Nodes"
* Narrative Behaviours
* Sociogram Prompt "Display Edges"
- [ ] Sociogram prompt display edge is disabled for the selected edge; it should be *selected* and disabled, so that the selected edge is always "on": 
image

Note, the shortcut to preview code on windows is ctrl + forward slash, if we're advertising that for users.

**Comment by rebeccamadsen** [comment]
- [ ] A boolean choice variable can have both options styled as "negative" - intentional or not?
- [ ] A datetime variable can have end dates created that are prior to beginning dates, but interviewer chokes on this
- [ ] Warning when clicking on Side Panels in Name Generator:
```
Warning: Failed prop type: Invalid prop `input.value` of type `string` supplied to `<<anonymous>>`, expected an array.
    in Unknown (created by sortableList)
    in sortableList (created by ConnectFunction)
    in ConnectFunction (created by renameProp(Connect(sortableList)))
    in renameProp(Connect(sortableList)) (created by defaultProps(renameProp(Connect(sortableList))))
    in defaultProps(renameProp(Connect(sortableList))) (created by ConnectedField)
    in ConnectedField (created by ConnectFunction)
    in ConnectFunction (created by Connect(ConnectedField))
    in Connect(ConnectedField) (created by Field)
    in Field (created by Context.Consumer)
    in Hoc (created by Field)
    in Field (created by NodePanels)
```
- [ ] Warnings when clicking on Create New Field in Name Generator:
```
Warning: Failed prop type: The prop `metaForType` is marked as required in `PromptFields`, but its value is `undefined`.
    in PromptFields (created by withHandlers(PromptFields))
    in withHandlers(PromptFields) (created by ConnectFunction)
    in ConnectFunction (created by EditableList)
    in form (created by Form)
    in Form (created by Form(Form))
    in Form(Form) (created by ConnectFunction)
```
```
Warning: Failed prop type: The prop `variableType` is marked as required in `ValidationSection`, but its value is `null`.
    in ValidationSection (created by PromptFields)
    in PromptFields (created by withHandlers(PromptFields))
    in withHandlers(PromptFields) (created by ConnectFunction)
    in ConnectFunction (created by EditableList)
    in form (created by Form)
    in Form (created by Form(Form))
    in Form(Form) (created by ConnectFunction)
    in ConnectFunction (created by Connect(Form(Form)))
```
- [ ] Warnings when clicking on Create New Node Type in Name Generator:
```
Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Editor`, expected `function`.
    in Editor (created by Form(Editor))
    in Form(Editor) (created by ConnectFunction)
    in ConnectFunction (created by Connect(Form(Editor)))
    in Connect(Form(Editor)) (created by ReduxForm)
    in ReduxForm (created by Context.Consumer)
    in Hoc (created by ReduxForm)
    in ReduxForm (created by withStateHandlers(ReduxForm))
    in withStateHandlers(ReduxForm) (created by withHandlers(withStateHandlers(ReduxForm)))
    in withHandlers(withStateHandlers(ReduxForm)) (created by withProps(withHandlers(withStateHandlers(ReduxForm))))
    in withProps(withHandlers(withStateHandlers(ReduxForm))) (created by ConnectFunction)
    in ConnectFunction (created by EditorScreen)
```
```
Warning: Failed prop type: The prop `input.name` is marked as required in `Radio`, but its value is `undefined`.
    in Radio (created by IconOption)
    in IconOption (created by RadioGroup)
    in div (created by RadioGroup)
    in div (created by RadioGroup)
    in RadioGroup (created by ConnectedField)
    in ConnectedField (created by ConnectFunction)
    in ConnectFunction (created by Connect(ConnectedField))
    in Connect(ConnectedField) (created by Field)
    in Field (created by Context.Consumer)
    in Hoc (created by Field)
    in Field (created by ValidatedField)
    in ValidatedField (created by TypeEditor)
```
- [ ] Warning in Ordinal Bin prompt, when canceling instead of creating an ordinal variable:
```
Warning: Failed prop type: The prop `label` is marked as required in `SimpleVariablePill`, but its value is `null`.
    in SimpleVariablePill (created by VariablePicker)
    in VariablePicker (created by ConnectedField)
    in ConnectedField (created by ConnectFunction)
    in ConnectFunction (created by Connect(ConnectedField))
    in Connect(ConnectedField) (created by Field)
    in Field (created by Context.Consumer)
    in Hoc (created by Field)
    in Field (created by ValidatedField)
    in ValidatedField (created by PromptFields)
    in div (created by Row)
    in Row (created by PromptFields)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Section)
    in Ma
```
- [ ] Warning in Categorical in creating a categorical variable with only one option:
```
Warning: Failed prop type: Invalid prop `optionsForVariableDraft[0].value` supplied to `PromptFields`.
    in PromptFields (created by withHandlers(PromptFields))
    in withHandlers(PromptFields) (created by ConnectFunction)
    in ConnectFunction (created by lifecycle(Connect(withHandlers(PromptFields))))
    in lifecycle(Connect(withHandlers(PromptFields))) (created by ConnectFunction)
    in ConnectFunction (created by EditableList)
    in form (created by Form)
    in Form (created by Form(Form))
    in Form(Form) (created by ConnectFunction)
    in ConnectFunction (created by Connect(Form(Form)))
    in Connect(Form(Form)) (created by ReduxForm)
    in ReduxForm (created by Context.Consumer)
    in Hoc (created by ReduxForm)
    in ReduxForm (created by InlineEditScreen)
    in div (created by Layout)
    in Layout (created by InlineEditScreen)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by InlineEditScreen)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by InlineEditScreen)
    in div (created by InlineEditScreen)
    in Ma
    in Unknown (created by InlineEditScreen)
    in InlineEditScreen (created by ConnectFunction)
    in ConnectFunction (created by () => `Window(${getDisplayName(WrappedComponent)})`)
    in () => `Window(${getDisplayName(WrappedComponent)})` (created by getContext(() => `Window(${getDisplayName(WrappedComponent)})`))
    in getContext(() => `Window(${getDisplayName(WrappedComponent)})`) (created by EditableList)
    in ka
    in Unknown (created by EditableList)
```
- [ ] Warning when adding an image to an Information Stage:
```
Warning: Failed prop type: The prop `url` is marked as required in `BackgroundImage`, but its value is `undefined`.
    in BackgroundImage (created by ItemPreview)
    in ItemPreview (created by ConnectFunction)
    in ConnectFunction (created by GridItem)
    in div (created by GridItem)
    in div (created by GridItem)
    in q (created by Context.Consumer)
    in B (created by GridItem)
    in div (created by GridItem)
    in GridItem (created by Grid)
    in div (created by Grid)
    in Resizable (created by GridItem)
    in DraggableCore (created by GridItem)
    in GridItem (created by ReactGridLayout)
    in div (created by ReactGridLayout)
    in ReactGridLayout (created by Grid)
    in div (created by Grid)
    in Grid (created by ConnectFunction)
```
- [ ] Warning on Alter form when selecting a previously created ordinal variable, and no preview image is selected:
```
Warning: Failed prop type: The prop `image` is marked as required in `InputPreview`, but its value is `undefined`.
    in InputPreview (created by PromptFields)
    in PromptFields (created by withHandlers(PromptFields))
    in withHandlers(PromptFields) (created by ConnectFunction)
    in ConnectFunction (created by EditableList)
    in form (created by Form)
    in Form (created by Form(Form))
    in Form(Form) (created by ConnectFunction)
    in ConnectFunction (created by Connect(Form(Form)))
    in Connect(Form(Form)) (created by ReduxForm)
    in ReduxForm (created by Context.Consumer)
    in Hoc (created by ReduxForm)
    in ReduxForm (created by InlineEditScreen)
    in div (created by Layout)
    in Layout (created by InlineEditScreen)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by InlineEditScreen)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by InlineEditScreen)
    in div (created by InlineEditScreen)
    in Ma
    in Unknown (created by InlineEditScreen)
    in InlineEditScreen (created by ConnectFunction)
    in ConnectFunction (created by () => `Window(${getDisplayName(WrappedComponent)})`)
    in () => `Window(${getDisplayName(WrappedComponent)})` (created by getContext(() => `Window(${getDisplayName(WrappedComponent)})`))
    in getContext(() => `Window(${getDisplayName(WrappedComponent)})`) (created by EditableList)
    in ka
    in Unknown (created by EditableList)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Section)
    in Ma
    in Unknown (created by Section)
    in fieldset (created by Section)
    in Section (created by EditableList)
    in EditableList (created by ConnectFunction)
    in ConnectFunction (created by withHandlers(Connect(EditableList)))
    in withHandlers(Connect(EditableList)) (created by withStateHandlers(withHandlers(Connect(EditableList))))
    in withStateHandlers(withHandlers(Connect(EditableList))) (created by ConnectFunction)
    in ConnectFunction (created by defaultProps(Connect(withStateHandlers(withHandlers(Connect(EditableList))))))
    in defaultProps(Connect(withStateHandlers(withHandlers(Connect(EditableList))))) (created by defaultProps(defaultProps(Connect(withStateHandlers(withHandlers(Connect(EditableList)))))))
    in defaultProps(defaultProps(Connect(withStateHandlers(withHandlers(Connect(EditableList)))))) (created by Form)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Section)
    in Ma
    in Unknown (created by Section)
    in fieldset (created by Section)
    in Section (created by Form)
    in Form (created by withProps(Form))
    in withProps(Form) (created by withProps(withProps(Form)))
    in withProps(withProps(Form)) (created by withHandlers(withProps(withProps(Form))))
    in withHandlers(withProps(withProps(Form))) (created by ConnectFunction)
    in ConnectFunction (created by ConnectFunction)
    in ConnectFunction (created by Editor)
    in div (created by Layout)
    in Layout (created by Editor)
    in form (created by Form)
    in Form (created by Context.Consumer)
    in Hoc (created by Form)
    in Form (created by Editor)
    in Editor (created by Form(Editor))
    in Form(Editor) (created by ConnectFunction)
    in ConnectFunction (created by Connect(Form(Editor)))
    in Connect(Form(Editor)) (created by ReduxForm)
    in ReduxForm (created by Context.Consumer)
    in Hoc (created by ReduxForm)
    in ReduxForm (created by withStateHandlers(ReduxForm))
    in withStateHandlers(ReduxForm) (created by StageEditor)
    in StageEditor (created by withHandlers(StageEditor))
    in withHandlers(StageEditor) (created by ConnectFunction)
    in ConnectFunction (created by ConnectFunction)
    in ConnectFunction (created by defaultProps(Connect(Connect(withHandlers(StageEditor)))))
    in defaultProps(Connect(Connect(withHandlers(StageEditor)))) (created by EditorScreen)
    in main (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Screen)
    in CardErrorBoundary (created by Screen)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Screen)
    in div (created by Screen)
    in Screen (created by EditorScreen)
    in EditorScreen (created by ConnectFunction)
    in ConnectFunction (created by withProps(Connect(EditorScreen)))
    in withProps(Connect(EditorScreen)) (created by withHandlers(withProps(Connect(EditorScreen))))
    in withHandlers(withProps(Connect(EditorScreen))) (created by ConnectFunction)
    in ConnectFunction (created by Screens)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Screens)
    in Ma
    in Unknown (created by Screens)
    in Screens (created by Routes)
    in Routes (created by AppView)
    in AppErrorBoundary (created by AppView)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by AppView)
    in AppView (created by Context.Consumer)
    in Route (created by ViewManager)
    in Switch (created by ViewManager)
    in Router (created by HashRouter)
    in HashRouter (created by ViewManager)
    in ViewManager
    in PersistGate
    in Provider
console.<computed> @ index.js:1
printWarning @ checkPropTypes.js:20
checkPropTypes @ checkPropTypes.js:82
validatePropTypes @ react.development.js:1714
createElementWithValidation @ react.development.js:1813
PromptFields @ FieldFields.js:118
renderWithHooks @ react-dom.development.js:14803
updateFunctionComponent @ react-dom.development.js:17034
beginWork @ react-dom.development.js:18610
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
index.js:1 Warning: Failed prop type: The prop `label` is marked as required in `InputPreview`, but its value is `undefined`.
    in InputPreview (created by PromptFields)
    in PromptFields (created by withHandlers(PromptFields))
    in withHandlers(PromptFields) (created by ConnectFunction)
    in ConnectFunction (created by EditableList)
    in form (created by Form)
    in Form (created by Form(Form))
    in Form(Form) (created by ConnectFunction)
    in ConnectFunction (created by Connect(Form(Form)))
    in Connect(Form(Form)) (created by ReduxForm)
    in ReduxForm (created by Context.Consumer)
    in Hoc (created by ReduxForm)
    in ReduxForm (created by InlineEditScreen)
    in div (created by Layout)
    in Layout (created by InlineEditScreen)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by InlineEditScreen)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by InlineEditScreen)
    in div (created by InlineEditScreen)
    in Ma
    in Unknown (created by InlineEditScreen)
    in InlineEditScreen (created by ConnectFunction)
    in ConnectFunction (created by () => `Window(${getDisplayName(WrappedComponent)})`)
    in () => `Window(${getDisplayName(WrappedComponent)})` (created by getContext(() => `Window(${getDisplayName(WrappedComponent)})`))
    in getContext(() => `Window(${getDisplayName(WrappedComponent)})`) (created by EditableList)
    in ka
    in Unknown (created by EditableList)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Section)
    in Ma
    in Unknown (created by Section)
    in fieldset (created by Section)
    in Section (created by EditableList)
    in EditableList (created by ConnectFunction)
    in ConnectFunction (created by withHandlers(Connect(EditableList)))
    in withHandlers(Connect(EditableList)) (created by withStateHandlers(withHandlers(Connect(EditableList))))
    in withStateHandlers(withHandlers(Connect(EditableList))) (created by ConnectFunction)
    in ConnectFunction (created by defaultProps(Connect(withStateHandlers(withHandlers(Connect(EditableList))))))
    in defaultProps(Connect(withStateHandlers(withHandlers(Connect(EditableList))))) (created by defaultProps(defaultProps(Connect(withStateHandlers(withHandlers(Connect(EditableList)))))))
    in defaultProps(defaultProps(Connect(withStateHandlers(withHandlers(Connect(EditableList)))))) (created by Form)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Section)
    in Ma
    in Unknown (created by Section)
    in fieldset (created by Section)
    in Section (created by Form)
    in Form (created by withProps(Form))
    in withProps(Form) (created by withProps(withProps(Form)))
    in withProps(withProps(Form)) (created by withHandlers(withProps(withProps(Form))))
    in withHandlers(withProps(withProps(Form))) (created by ConnectFunction)
    in ConnectFunction (created by ConnectFunction)
    in ConnectFunction (created by Editor)
    in div (created by Layout)
    in Layout (created by Editor)
    in form (created by Form)
    in Form (created by Context.Consumer)
    in Hoc (created by Form)
    in Form (created by Editor)
    in Editor (created by Form(Editor))
    in Form(Editor) (created by ConnectFunction)
    in ConnectFunction (created by Connect(Form(Editor)))
    in Connect(Form(Editor)) (created by ReduxForm)
    in ReduxForm (created by Context.Consumer)
    in Hoc (created by ReduxForm)
    in ReduxForm (created by withStateHandlers(ReduxForm))
    in withStateHandlers(ReduxForm) (created by StageEditor)
    in StageEditor (created by withHandlers(StageEditor))
    in withHandlers(StageEditor) (created by ConnectFunction)
    in ConnectFunction (created by ConnectFunction)
    in ConnectFunction (created by defaultProps(Connect(Connect(withHandlers(StageEditor)))))
    in defaultProps(Connect(Connect(withHandlers(StageEditor)))) (created by EditorScreen)
    in main (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Screen)
    in CardErrorBoundary (created by Screen)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Screen)
    in div (created by Screen)
    in Screen (created by EditorScreen)
    in EditorScreen (created by ConnectFunction)
    in ConnectFunction (created by withProps(Connect(EditorScreen)))
    in withProps(Connect(EditorScreen)) (created by withHandlers(withProps(Connect(EditorScreen))))
    in withHandlers(withProps(Connect(EditorScreen))) (created by ConnectFunction)
    in ConnectFunction (created by Screens)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Screens)
    in Ma
    in Unknown (created by Screens)
    in Screens (created by Routes)
    in Routes (created by AppView)
    in AppErrorBoundary (created by AppView)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by AppView)
    in AppView (created by Context.Consumer)
    in Route (created by ViewManager)
    in Switch (created by ViewManager)
    in Router (created by HashRouter)
    in HashRouter (created by ViewManager)
    in ViewManager
    in PersistGate
    in Provider
console.<computed> @ index.js:1
printWarning @ checkPropTypes.js:20
checkPropTypes @ checkPropTypes.js:82
validatePropTypes @ react.development.js:1714
createElementWithValidation @ react.development.js:1813
PromptFields @ FieldFields.js:118
renderWithHooks @ react-dom.development.js:14803
updateFunctionComponent @ react-dom.development.js:17034
beginWork @ react-dom.development.js:18610
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
index.js:1 Warning: Failed prop type: The prop `description` is marked as required in `InputPreview`, but its value is `undefined`.
    in InputPreview (created by PromptFields)
    in PromptFields (created by withHandlers(PromptFields))
    in withHandlers(PromptFields) (created by ConnectFunction)
    in ConnectFunction (created by EditableList)
    in form (created by Form)
    in Form (created by Form(Form))
    in Form(Form) (created by ConnectFunction)
    in ConnectFunction (created by Connect(Form(Form)))
    in Connect(Form(Form)) (created by ReduxForm)
    in ReduxForm (created by Context.Consumer)
    in Hoc (created by ReduxForm)
    in ReduxForm (created by InlineEditScreen)
    in div (created by Layout)
    in Layout (created by InlineEditScreen)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by InlineEditScreen)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by InlineEditScreen)
    in div (created by InlineEditScreen)
    in Ma
    in Unknown (created by InlineEditScreen)
    in InlineEditScreen (created by ConnectFunction)
    in ConnectFunction (created by () => `Window(${getDisplayName(WrappedComponent)})`)
    in () => `Window(${getDisplayName(WrappedComponent)})` (created by getContext(() => `Window(${getDisplayName(WrappedComponent)})`))
    in getContext(() => `Window(${getDisplayName(WrappedComponent)})`) (created by EditableList)
    in ka
    in Unknown (created by EditableList)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Section)
    in Ma
    in Unknown (created by Section)
    in fieldset (created by Section)
    in Section (created by EditableList)
    in EditableList (created by ConnectFunction)
    in ConnectFunction (created by withHandlers(Connect(EditableList)))
    in withHandlers(Connect(EditableList)) (created by withStateHandlers(withHandlers(Connect(EditableList))))
    in withStateHandlers(withHandlers(Connect(EditableList))) (created by ConnectFunction)
    in ConnectFunction (created by defaultProps(Connect(withStateHandlers(withHandlers(Connect(EditableList))))))
    in defaultProps(Connect(withStateHandlers(withHandlers(Connect(EditableList))))) (created by defaultProps(defaultProps(Connect(withStateHandlers(withHandlers(Connect(EditableList)))))))
    in defaultProps(defaultProps(Connect(withStateHandlers(withHandlers(Connect(EditableList)))))) (created by Form)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Section)
    in Ma
    in Unknown (created by Section)
    in fieldset (created by Section)
    in Section (created by Form)
    in Form (created by withProps(Form))
    in withProps(Form) (created by withProps(withProps(Form)))
    in withProps(withProps(Form)) (created by withHandlers(withProps(withProps(Form))))
    in withHandlers(withProps(withProps(Form))) (created by ConnectFunction)
    in ConnectFunction (created by ConnectFunction)
    in ConnectFunction (created by Editor)
    in div (created by Layout)
    in Layout (created by Editor)
    in form (created by Form)
    in Form (created by Context.Consumer)
    in Hoc (created by Form)
    in Form (created by Editor)
    in Editor (created by Form(Editor))
    in Form(Editor) (created by ConnectFunction)
    in ConnectFunction (created by Connect(Form(Editor)))
    in Connect(Form(Editor)) (created by ReduxForm)
    in ReduxForm (created by Context.Consumer)
    in Hoc (created by ReduxForm)
    in ReduxForm (created by withStateHandlers(ReduxForm))
    in withStateHandlers(ReduxForm) (created by StageEditor)
    in StageEditor (created by withHandlers(StageEditor))
    in withHandlers(StageEditor) (created by ConnectFunction)
    in ConnectFunction (created by ConnectFunction)
    in ConnectFunction (created by defaultProps(Connect(Connect(withHandlers(StageEditor)))))
    in defaultProps(Connect(Connect(withHandlers(StageEditor)))) (created by EditorScreen)
    in main (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Screen)
    in CardErrorBoundary (created by Screen)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Screen)
    in div (created by Screen)
    in Screen (created by EditorScreen)
    in EditorScreen (created by ConnectFunction)
    in ConnectFunction (created by withProps(Connect(EditorScreen)))
    in withProps(Connect(EditorScreen)) (created by withHandlers(withProps(Connect(EditorScreen))))
    in withHandlers(withProps(Connect(EditorScreen))) (created by ConnectFunction)
    in ConnectFunction (created by Screens)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by Screens)
    in Ma
    in Unknown (created by Screens)
    in Screens (created by Routes)
    in Routes (created by AppView)
    in AppErrorBoundary (created by AppView)
    in div (created by ForwardRef)
    in e (created by ForwardRef)
    in ForwardRef (created by AppView)
    in AppView (created by Context.Consumer)
    in Route (created by ViewManager)
    in Switch (created by ViewManager)
    in Router (created by HashRouter)
    in HashRouter (created by ViewManager)
    in ViewManager
    in PersistGate
    in Provider
```

**Comment by jthrilly** [comment]
Yeah, I'm going to ignore protype warning for now. Most are to do with conditionally rendering and/or dependencies between sections.

**Comment by rebeccamadsen** [comment]
> Yeah, I'm going to ignore protype warning for now. Most are to do with conditionally rendering and/or dependencies between sections.

Makes sense.

> Check out this tip for when you need to post long stuff on GH: https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d

Oh, I love this - thanks for the tip!

**Comment by jthrilly** [comment]
@rebeccamadsen - please could you put the console warnings into an issue, and the date picker issue into a separate issue?

**Comment by rebeccamadsen** [comment]
See [here](https://github.com/complexdatacollective/Architect/issues/749) and [here](https://github.com/complexdatacollective/Architect/issues/750) for date picker and console warning issues.

**Pull request merged**
